### ISSUE TITLE
SPDFM Responsibilities -  possible abstraction issue

### ISSUE THREAD

**Issue by muralidn** [shmouses/SPDFEM#10]
Point no 2 (Read input ...) in the SPDFM responsibilities sound too detailed, and can be abstracted. 

> SPDFM Responsibilities:
> - Inform user of their responsibilities in using SPDFM
> - Read input files and inform user if the file formats are wrong or information are missing.
> - Interact with FEniCS toolbox.
> - Display the calculated data.
> - Export data in the correct format(s).

I have doubts over the last 2 points as well; they are essentials ways to output the data. However, I am not sure about
the abstraction required in this section. Dr. @smiths can you please comment.

**Comment by shmouses** [comment]
I agree, Dr. Smith should comment on this because the level of abstraction is no still very clear for me as well.

**Comment by smiths** [comment]
@shmouses, @muralidn is correct that the list of responsibilities should be more abstract.  Unless it is an imposed design constraint (it might be, say if your supervisor requires it), you shouldn't mention FEniCS by name.  You can call it an external finite element toolbox.  This allows for the possibility of using a different toolbox in your implementation.  The last two items are about the output.  At this abstraction, you can just say that the outputs will be calculated.  Ideally, you should say at an abstract level what the outputs are.  (For a mechanics problem, as an example, you might say, the output is the deformed shape, without saying how the deformation will be represented.)

**Comment by shmouses** [comment]
Issue resolved: f4201d4adbdc3d5f5d5fa0d5dd3fe6c849ba9a90
