### ISSUE TITLE
NFR1

### ISSUE THREAD

**Issue by muralidn** [shmouses/SPDFEM#11]
@shmouses 

![image](https://user-images.githubusercontent.com/71282513/95950074-8c89b500-0e11-11eb-950c-6e31cdf6b3ff.png)

I am not sure about this requirement. The 8GB RAM and the "Desktop computer" requirements appear to be too specific, and the "decent CPU" appears to be vague. 

Usually, the CPU, RAM, etc are packaged into a "minimum specification". For example, "The application shall execute in an environment with a minimum specification as showing in Table-X".

**Comment by shmouses** [comment]
I agree with the contrast between the specification of CPU and the RAM I will specify CPU as well. I really liked the suggestion about the table, thank you so much for the keen suggestion, I will probably create a table like you mentioned.
