### ISSUE TITLE
SRS review (CAS 741)

### ISSUE THREAD

**Issue by shmouses** [shmouses/SPDFEM#2]
Dear Dr. Smith,
I really appreciate if you can review my SRS. (at https://github.com/shmouses/SPDFM/tree/master/docs/SRS)

The commit pushed before 12:00 pm:                                         
                                                          ade41750dbdc725d64556f7c9373739f7b926661
                                https://github.com/shmouses/SPDFM/commit/ade41750dbdc725d64556f7c9373739f7b926661

I really appreciate if you could comment the commit I pushed almost 2 hr later:
                                                            ff328ffaa07d0a7d3074a547e4009acc3c6b2b72
                                 https://github.com/shmouses/SPDFM/commit/ff328ffaa07d0a7d3074a547e4009acc3c6b2b72
Best regards,
Shayan

**Comment by smiths** [comment]
Thank you @shmouses.  I'll get to the review as soon as I can.  I'll review the version you pushed after the deadline.  :smile:

**Comment by shmouses** [comment]
Thank you so much Dr. Smith!

**Comment by smiths** [comment]
At the start of my review, I noticed a few spelling mistakes that are fixed in 99990cc.  I also noticed that BibTeX doesn't work on the repo version because the bib entries are missing.  @shmouses, you might want to update your bib file.  :smile:

**Comment by smiths** [comment]
Feedback on the SRS is given in 31f0eb0.  Please create any associated issues that you need.

**Comment by shmouses** [comment]
Thank you so much for the comments Dr. Smith (@smiths). I am sorry for the problem that you had with the tex file. Sorry if there were some discrepancies in the PDF file, thanks for commenting on them, the reason is that I am currently changing the SRS with MIS and MG after changing it with respect to VnV. But I still didn't have time to delete some previous IMs, update my Theoretical models with respect to the recent changes, change labels, and also update my traceability tables. SO it is experiencing its transition phase at the moment. I will make sure that I fix all of them for the final document.

**Comment by smiths** [comment]
Sounds good @shmouses.
