### ISSUE TITLE
MG: unlikely change label

### ISSUE THREAD

**Issue by gabrielasd** [shmouses/SPDFEM#35]
The second unlikely change in subsection 4.2 appears with an "AC" label.
bellow's latex command was taken from that section in the Module Guide:
\item[\refstepcounter{ucnum} \actheacnum **\label{acForm}**:] Nonlocal surface plasmon hydrodynamic formulations.

and this is how it shows in the document:
![uclabel](https://user-images.githubusercontent.com/26312264/100422384-36d33a00-3058-11eb-8401-69a21d213b2f.png)

**Comment by shmouses** [comment]
Thanks a lot Gabi, it is resolved in : 5dd4292c1b1bace6e1d51a61bbcfd511d5903964
