### ISSUE TITLE
MIS: word format

### ISSUE THREAD

**Issue by gabrielasd** [shmouses/SPDFEM#36]
I noticed the word expand-ability used in subsection 10.4.4 of the MIS. Is this word correct or it should have been _expandability_?

![expandabilitytypo](https://user-images.githubusercontent.com/26312264/100423394-e957cc80-3059-11eb-9d58-8c7f7b932e7b.png)

**Comment by shmouses** [comment]
Thanks a lot @gabrielasd, resolved in bd9514e494d0c4bf6c405e22d3d758e15dd44999
