### ISSUE TITLE
MIS: exception declaration

### ISSUE THREAD

**Issue by gabrielasd** [shmouses/SPDFEM#37]
**exc :=** should be used when declaring exceptions

As an example I took the image below from 
https://github.com/smiths/swhs/blob/master/docs/Design/MIS/PCM_MIS.pdf
![exceptiondeclaration](https://user-images.githubusercontent.com/26312264/100424151-2f616000-305b-11eb-8460-56a323a0d41e.png)

**Comment by shmouses** [comment]
Thanks a lot @gabrielasd, resolved: b9a75ce187c312f40ef8ae59e8eaeb6e451b6ae6
