### ISSUE TITLE
MIS: ParamMPfile name typo

### ISSUE THREAD

**Issue by gabrielasd** [shmouses/SPDFEM#38]
There is a typo in a file name (ParamMPfile) under subsection 7.4.2
![subsection7 4 2_typo](https://user-images.githubusercontent.com/26312264/100424895-42c0fb00-305c-11eb-8f25-3e7d51a84b72.png)

**Comment by shmouses** [comment]
Thanks @gabrielasd, resolved : 3064b3f55846924c507a735ab5e13ebc852665f6
