### ISSUE TITLE
MIS: naming of variables in equation vs data structure names

### ISSUE THREAD

**Issue by gabrielasd** [shmouses/SPDFEM#39]
Are the variables stored by the Data Structure Module (data.variablename) used in the equation solved by FEniCS toolbox (declared in Section 11)? If so, could this correspondence be shown by using the actual equation symbols to name the data variables?
For example: instead of data.mu0 use data.$\mu_0$  (even though in the implementation data.mu0 is the name going to be used.)
![redefine_equation](https://user-images.githubusercontent.com/26312264/100426671-430ec580-305f-11eb-9625-5ec6d39a711c.png)

**Comment by shmouses** [comment]
resolved : 5dd4292c1b1bace6e1d51a61bbcfd511d5903964
