### ISSUE TITLE
MIS: object data type

### ISSUE THREAD

**Issue by gabrielasd** [shmouses/SPDFEM#40]
Is "object" a data type? If so maybe it should be defined in the Notation section.
![datatype](https://user-images.githubusercontent.com/26312264/100427995-5589fe80-3061-11eb-8db2-cee1b246b6e2.png)

**Comment by shmouses** [comment]
Thanks Gabi, resolved: 5dd4292c1b1bace6e1d51a61bbcfd511d5903964
