### ISSUE TITLE
Very minor issues in VnV document

### ISSUE THREAD

**Issue by shinsid** [shmouses/SPDFEM#41]
I found very minor issues - 

I think a word is missing here - 
![image](https://user-images.githubusercontent.com/12082585/101216832-35a09f00-364e-11eb-9f1d-97add3eb2ec4.png)

Minor typo here - 
![image](https://user-images.githubusercontent.com/12082585/101216886-51a44080-364e-11eb-9502-3b71508150df.png)

I think you are missing link/ref here - 
![image](https://user-images.githubusercontent.com/12082585/101216914-5b2da880-364e-11eb-8fb4-5e44244863da.png)

**Comment by shmouses** [comment]
Thanks a lot, resolved: 5dd4292c1b1bace6e1d51a61bbcfd511d5903964
