### ISSUE TITLE
Roadmap missing in the introduction section

### ISSUE THREAD

**Issue by muralidn** [shmouses/SPDFEM#5]
@shmouses 
According to the SRS template, in addition to introducing the problem, the reader is expected to provide a roadmap about the subsequent sections in section 2.

![image](https://user-images.githubusercontent.com/71282513/95672007-9d8cb900-0bba-11eb-897b-6ff338ddd3d4.png)

**Comment by smiths** [comment]
Good feedback @shmouses.  @shmouses, when you close this issue, please include the commit hash where the roadmap is added.

**Comment by shmouses** [comment]
Issue resolved: 976793ad5e6347f49b9ca0abead504bbcacefbda
