### ISSUE TITLE
Abstraction of the Scope

### ISSUE THREAD

**Issue by muralidn** [shmouses/SPDFEM#6]
@shmouses 

In section 2.2, scope, as highlighted in the picture below,

![image](https://user-images.githubusercontent.com/71282513/95674121-c36e8980-0bcb-11eb-9398-829f3ab1b4f7.png)

The first sentence (highlighted in orange) appears to discusses the input contains supplied by the user, which is a low-level detail that should not be in the scope. 

The second sentence (highlighted in yellow) appears to be at an appropriate level for the scope, however, the phrase "for the moment" puts it along the lines of likey changes. The project scope is always fixed, and any tentative change there are assumptions.

**Comment by shmouses** [comment]
Issue resolved: cd19c116312f4d8e574e0856b9c92c4884b4f12c
