### ISSUE TITLE
Ambiguity in user characteristics

### ISSUE THREAD

**Issue by muralidn** [shmouses/SPDFEM#7]
@shmouses 

The User characteristics state that end-user should have a general understanding of programming (as highlighted below),

![image](https://user-images.githubusercontent.com/71282513/95678971-8ca96b00-0bed-11eb-928b-cad43bf0ab7c.png)

If the user does require knowledge of programming, it should be elaborated. For example, it is a common practice to input the specifications of an application in XML (which requires pre-requisite knowledge), in which case XML should be specified.

**Comment by shmouses** [comment]
Thanks! I will think about this,  I should decide on the level of abstractness.

**Comment by smiths** [comment]
@shmouses, if you make changes in your SRS to address this issue, please include the hash of the commit that closes the issue.

**Comment by shmouses** [comment]
Issue resolved: 5387a406f550896642a204ce30b83f0da6f3f934
