### ISSUE TITLE
User responsibilities - repeating points

### ISSUE THREAD

**Issue by muralidn** [shmouses/SPDFEM#8]
I believe the second bullet of the User characteristics is implied in the first? Unless the second bullet is a separate procedure in itself.

![image](https://user-images.githubusercontent.com/71282513/95679910-71d9f500-0bf3-11eb-855a-d596c78e88e8.png)

**Comment by shmouses** [comment]
They are not the same. Sparsely meshed geometry is a correct input but it affects the quality of the result. Users should be aware of that.
